export const popularSymbols = [
  { label: 'Bitcoin (BTC)', value: 'BINANCE:BTCUSDT' },
  { label: 'Ethereum (ETH)', value: 'BINANCE:ETHUSDT' },
  { label: 'Solana (SOL)', value: 'BINANCE:SOLUSDT' },
  { label: 'Ripple (XRP)', value: 'BINANCE:XRPUSDT' },
  { label: 'Cardano (ADA)', value: 'BINANCE:ADAUSDT' },
  { label: 'Dogecoin (DOGE)', value: 'BINANCE:DOGEUSDT' },
  { label: 'Apple Inc. (AAPL)', value: 'AAPL' },
  { label: 'Amazon.com Inc. (AMZN)', value: 'AMZN' },
  { label: 'Alphabet Inc. (GOOGL)', value: 'GOOGL' },
  { label: 'Microsoft Corp. (MSFT)', value: 'MSFT' },
  { label: 'Meta Platforms Inc. (META)', value: 'META' },
  { label: 'NVIDIA Corp. (NVDA)', value: 'NVDA' },
  { label: 'Tesla Inc. (TSLA)', value: 'TSLA' },
  { label: 'Netflix Inc. (NFLX)', value: 'NFLX' },
  { label: 'Berkshire Hathaway Inc. (BRK.A)', value: 'BRK.A' },
  { label: 'JPMorgan Chase & Co. (JPM)', value: 'JPM' },
  { label: 'Visa Inc. (V)', value: 'V' },
  { label: 'Walmart Inc. (WMT)', value: 'WMT' },
  { label: 'Procter & Gamble Co. (PG)', value: 'PG' },
  { label: 'Johnson & Johnson (JNJ)', value: 'JNJ' },
  { label: 'Coca-Cola Co. (KO)', value: 'KO' },
  { label: 'Pfizer Inc. (PFE)', value: 'PFE' },
  { label: 'Bank of America Corp. (BAC)', value: 'BAC' },
  { label: 'Intel Corp. (INTC)', value: 'INTC' },
  { label: 'AMD (Advanced Micro Devices) (AMD)', value: 'AMD' },
];
